### ISSUE TITLE
Chlorotrifluoroethylene as vacuum freezer refrigerent

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Rong-GT#10]

**Comment by MFernflower** [comment]
"CTFE has a carbon-carbon double bond and so can be polymerized to form polychlorotrifluoroethylene or copolymerized to produce the plastic ECTFE."

**Comment by Rongmario** [comment]
Polychlorotrifluoroethylene is planned for either IV/LuV parts

**Comment by Rongmario** [comment]
And I wanted to utilize ECTFE for anything that needs corrosion resistence, haven't thought of an idea though. Perhaps for TGI, they could be Powersuit material.

**Comment by MFernflower** [comment]
Would also be good for storing HF because of the whole glass thing

**Comment by Rongmario** [comment]
Expand?

**Comment by MFernflower** [comment]
Hydrofluoric acid cannot be kept in glass containers as it will weaken them and cause them to leak dangerous HF everywhere 


Hydrofluoric acid needs to be kept in plastic jugs and I think polyethylene or ectfe would be fine

**Comment by Rongmario** [comment]
Ok thought thats what you mean of HF, it might impact gameplay too much but I'll note

**Comment by MFernflower** [comment]
Oops
