### ISSUE TITLE
[7.6.0] Rubber Leaves, Saplings textures

### ISSUE THREAD

**Issue by ilvrak** [EnderExtreme/Rong-GT#14]
![2019-04-19_11 47 23](https://user-images.githubusercontent.com/16130834/56404411-1f877480-6299-11e9-829d-8bea056fde45.png)
![2019-04-19_11 47 32](https://user-images.githubusercontent.com/16130834/56404412-20200b00-6299-11e9-9d93-95470aa13ffc.png)

**Comment by Rongmario** [comment]
Fixed in dev, next build pushing in 1 or 2 days

**Comment by Rongmario** [comment]
Uploading in an hour
