### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Armagedon13** [EnderExtreme/Rong-GT#2]
Forge: 14.23.5.2774
Gregtech  chill version: 1.12.2-6.13.0
Anothers mods: 
industrialcraft-2-2.8.111-ex112
jei_1.12.2-4.14.4.264
CodeChickenLib-1.12.2-3.2.2.353-universal
Crash report:[https://pastebin.com/HvEzCYvK](url)

**Comment by Rongmario** [comment]
I'll upload a version without any crashes tomorrow.

**Comment by Rongmario** [comment]
Fixed. I'll upload build in a bit.
