### ISSUE TITLE
干预匠魂炉子，导致匠魂炉子不可以熔炼！

### ISSUE THREAD

**Issue by cdcp998** [EnderExtreme/Rong-GT#26]
![K}UL`YUA2TUZK@JQUM75)JL](https://user-images.githubusercontent.com/1726165/57972411-85683880-79cc-11e9-826c-adda014ac7ab.png)

**Comment by Rongmario** [comment]
好怪, 我看看

最近在試試看把格雷支持IC2C 所以有點忙

**Comment by cdcp998** [comment]
没关系，最近可能找出你的mod很多兼容性bug 或者功能bug。估计要辛苦你了。
谢谢。

**Comment by Rongmario** [comment]
這樣也好, 修更多!

**Comment by cdcp998** [comment]
那个。能不能催更下=。=

**Comment by Rongmario** [comment]
抱歉, 這幾天忙得不過來, 在重寫這個模組! https://minecraft.curseforge.com/projects/gregtech-chill-edition/files/2713771

**Comment by cdcp998** [comment]
谢谢、辛苦了。。
