### ISSUE TITLE
Overhaul Magic Energy Absorbers

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Rong-GT#31]
https://github.com/EnderExtreme/Toxic-Garbage-Island/issues/162

**Comment by kotelkonrad** [comment]
add accepting ember crystal from embers mod
and 
mana from wizardry
https://ftb.gamepedia.com/Wizardry

**Comment by MFernflower** [comment]
Perhaps also have it accept power from those RF crystals from a mod that name escapes me? @Rongmario Great to see stuff being done to improve GT and gröögistry in general

**Comment by Rongmario** [comment]
Moved to GTi.
