### ISSUE TITLE
steam machine Not work

### ISSUE THREAD

**Issue by cdcp998** [EnderExtreme/Rong-GT#42]
![CV}QSM(X2@R5JYUZIK20T`0](https://user-images.githubusercontent.com/1726165/58433553-64999480-80ea-11e9-972f-fd454d4e56b8.png)
![@~QEUQ2(D~NG7JW(EBFB{{1](https://user-images.githubusercontent.com/1726165/58433554-64999480-80ea-11e9-9862-33268851de88.png)
![~`}QU{F6 DUAW8L4_THZ{09](https://user-images.githubusercontent.com/1726165/58433555-65322b00-80ea-11e9-9a73-af094ae444ea.png)
![3W{T~LY2Q95Y$WM034WFEPB](https://user-images.githubusercontent.com/1726165/58433557-65322b00-80ea-11e9-9077-8a87b6a9f636.png)

关于蒸汽设备都无法正常工作。

**Comment by Rongmario** [comment]
知道了謝謝

**Comment by cdcp998** [comment]
感觉问题好多啊。。都不能正常玩耍了。
