### ISSUE TITLE
Crash issue!

### ISSUE THREAD

**Issue by NerdySpider** [EnderExtreme/Rong-GT#43]
I get a crash when I try to load the mod in my dev pack.
If it helps I also have shadows of Greg installed. not too sure if it's compatible though if it isn't please let me know.

https://paste.dimdev.org/etikosoron.mccrash

**Comment by Rongmario** [comment]
Yeah, I removed bolts altogether, that was the reason of the crash, so it seems to be incompatible with Shadow of Greg.
