### ISSUE TITLE
Serverside Crash w/ Thaumcraft 6

### ISSUE THREAD

**Issue by ghost** [EnderExtreme/Rong-GT#46]
This crash happens only on the server, and not the client. Forge versions are identical, and so too are the mods installed.

Here's the [crash report](https://hatebin.com/rsdrajyuib).
Forge version: `1.12.2 - 14.23.5.2854`
GTCE version: `7.8.0`
Thaumcraft version: `6.1.BETA26`

I've been searching around for a while trying to figure out how to stop GTCE's Thaumcraft compatibility stuff running, so I can resolve this on my end at least temporarily. Nothing though.

**Comment by Rongmario** [comment]
@Brittank88 this project is deprecated, check here for the successor: https://github.com/GregTech-Intergalactical
